#!/bin/bash

while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
        --region)
            REGION="$2"
            shift # past argument
            shift # past value
        ;;
        --profile)
            PROFILE="$2"
            shift # past argument
            shift # past value
        ;;
        --instance-id)
            INSTANCE_ID="$2"
            shift # past argument
            shift # past value
        ;;
        --local-port)
            LOCAL_PORT="$2"
            shift # past argument
            shift # past value
        ;;
        --remote-port)
            REMOTE_PORT="$2"
            shift # past argument
            shift # past value
        ;;
        --remote-host)
            REMOTE_HOST="$2"
            shift # past argument
            shift # past value
        ;;        
    esac
done

PARAMS=$(jq -n \
  --arg host "${REMOTE_HOST}" \
  --arg port "${REMOTE_PORT}" \
  --arg local "${LOCAL_PORT}" \
  '{
    host: [$host],
    portNumber: [$port],
    localPortNumber: [$local]
  }')

aws --profile ${PROFILE} --region ${REGION} ssm start-session --target ${INSTANCE_ID}   --document-name AWS-StartPortForwardingSessionToRemoteHost --parameters "${PARAMS}"


